// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjnqelwplalrsepzqotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbnFlbHdwbGFscnNlcHpxb3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjg2NTIsImV4cCI6MjA2ODk0NDY1Mn0.tSqdJ-zT9AIDhotT_0zWoKfetC1DYUxMw1TciT_9iPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});